/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javasql;

import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Yosep
 */
public class JavaSQL extends javax.swing.JFrame {

    /**
     * Creates new form JavaSQLGUI
     */
    
    Connection con;
    Statement st;
    PreparedStatement ps;
    CallableStatement cs;
    ResultSet rs;
    
    public JavaSQL() {
        initComponents();
        mostrarAlumnos();
        
    }

    public ArrayList<Alumnos> alumnosList(){
        
        ArrayList<Alumnos> alumnosList = new ArrayList<>();
        
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","ALU","ALU");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM Alumnos");
            
            Alumnos alumnos;
            
            while(rs.next()){
                
                alumnos = new Alumnos(rs.getInt("id"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("instituto"),rs.getString("poblacion"));
                alumnosList.add(alumnos);
            }
            
        }catch(Exception se){
            se.printStackTrace();
        }  
        
        return alumnosList;
    }
    
    public void mostrarAlumnos(){
        
        ArrayList<Alumnos> list = alumnosList();
        DefaultTableModel model = (DefaultTableModel) alumnosTB.getModel();
        Object[] row = new Object [100];
        for(int i = 0; i<list.size(); i++){
            
            row[0]=list.get(i).getId();
            row[1]=list.get(i).getNombre();
            row[2]=list.get(i).getApellido();
            row[3]=list.get(i).getInstituto();
            row[4]=list.get(i).getPoblacion();
            model.addRow(row);
        }
        
    }
    
    
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        alumnosTB = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        nombreTF = new javax.swing.JTextField();
        apellidoTF = new javax.swing.JTextField();
        institutosTF = new javax.swing.JTextField();
        poblacionTF = new javax.swing.JTextField();
        borrarBT = new javax.swing.JButton();
        modificarBT = new javax.swing.JButton();
        insertarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alumnosTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Instituto", "Poblacion"
            }
        ));
        alumnosTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alumnosTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(alumnosTB);

        jLabel1.setText("Id");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Institutos");

        jLabel5.setText("Poblacion");

        nombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTFActionPerformed(evt);
            }
        });

        poblacionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poblacionTFActionPerformed(evt);
            }
        });

        borrarBT.setText("Borrar");
        borrarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBTActionPerformed(evt);
            }
        });

        modificarBT.setText("Modificar");
        modificarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBTActionPerformed(evt);
            }
        });

        insertarBT.setText("Insertar");
        insertarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTF)
                            .addComponent(nombreTF)
                            .addComponent(apellidoTF)
                            .addComponent(institutosTF)
                            .addComponent(poblacionTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(insertarBT)
                        .addGap(18, 18, 18)
                        .addComponent(modificarBT)
                        .addGap(18, 18, 18)
                        .addComponent(borrarBT)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(institutosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poblacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarBT)
                    .addComponent(modificarBT)
                    .addComponent(insertarBT))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTFActionPerformed

    private void poblacionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poblacionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poblacionTFActionPerformed

    private void insertarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarBTActionPerformed
       
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","ALU","ALU");
            String query = "INSERT INTO ALUMNOS (id,nombre,apellido,instituto,poblacion) VALUES(?,?,?,?,?)";
            ps = con.prepareStatement(query);
            ps.setString(1, idTF.getText());
            ps.setString(2, nombreTF.getText());
            ps.setString(3, apellidoTF.getText());
            ps.setString(4, institutosTF.getText());
            ps.setString(5, poblacionTF.getText());
            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) alumnosTB.getModel();
            model.setRowCount(0);
            mostrarAlumnos();
            JOptionPane.showMessageDialog(null,"Insert realizado con exito");
            
        }catch(Exception se){
            se.printStackTrace();
        }
        
    }//GEN-LAST:event_insertarBTActionPerformed

    private void modificarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBTActionPerformed
        // TODO add your handling code here:
        
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","ALU","ALU");
            int row = alumnosTB.getSelectedRow();
            String value = (alumnosTB.getModel().getValueAt(row, 0).toString());
            String query = "UPDATE ALUMNOS SET id=?, nombre=?, apellido=?, instituto=?, poblacion=? WHERE id="+value;
            ps = con.prepareStatement(query);
            ps.setString(1, idTF.getText());
            ps.setString(2, nombreTF.getText());
            ps.setString(3, apellidoTF.getText());
            ps.setString(4, institutosTF.getText());
            ps.setString(5, poblacionTF.getText());
            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) alumnosTB.getModel();
            model.setRowCount(0);
            mostrarAlumnos();
            
            JOptionPane.showMessageDialog(null,"Delete realizado con exito");
            
        }catch(Exception se){
            se.printStackTrace();
        }
        
    }//GEN-LAST:event_modificarBTActionPerformed

    private void alumnosTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnosTBMouseClicked
        // TODO add your handling code here:
        
        int i = alumnosTB.getSelectedRow();
        TableModel model = alumnosTB.getModel();
        
        idTF.setText(model.getValueAt(i,0).toString());
        nombreTF.setText(model.getValueAt(i,1).toString());
        apellidoTF.setText(model.getValueAt(i,2).toString());
        institutosTF.setText(model.getValueAt(i,3).toString());
        poblacionTF.setText(model.getValueAt(i,4).toString());
        
    }//GEN-LAST:event_alumnosTBMouseClicked

    private void borrarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBTActionPerformed
        // TODO add your handling code here:
        
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","ALU","ALU");
            int row = alumnosTB.getSelectedRow();
            String value = (alumnosTB.getModel().getValueAt(row, 0).toString());
            String query = "DELETE FROM ALUMNOS WHERE id="+value;
            ps = con.prepareStatement(query);
            ps.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) alumnosTB.getModel();
            model.setRowCount(0);
            mostrarAlumnos();
            
            JOptionPane.showMessageDialog(null,"Borrado realizado con exito");
            
        }catch(Exception se){
            se.printStackTrace();
        }
        
    }//GEN-LAST:event_borrarBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaSQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alumnosTB;
    private javax.swing.JTextField apellidoTF;
    private javax.swing.JButton borrarBT;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton insertarBT;
    private javax.swing.JTextField institutosTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarBT;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JTextField poblacionTF;
    // End of variables declaration//GEN-END:variables
}
